sudo: required

language: sh

services:
  - docker

env:
  global:
    - IMAGE="robertdebock/docker-rpmbuild"

before_install:
- docker pull ${IMAGE}

install:
- docker run -v $(pwd):/build ${IMAGE}

script:
- find ./ -name '*.rpm'

deploy:
  - provider: s3
    access_key_id: ${S3KEY}
    secret_access_key: ${S3SECRET}
    bucket: "rpms"
    region: "eu-west-1"
    skip_cleanup: true
    local_dir: /build/RPMS
    on:
      branch: master
  - provider: s3
    access_key_id: ${S3KEY}
    secret_access_key: ${S3SECRET}
    bucket: "rpms"
    region: "eu-west-1"
    skip_cleanup: true
    local_dir: /build/SRPMS
    on:
      branch: master

notifications:
  email: false
